package Animals.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAnimals = createDescriptorForAnimals();
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCat = createDescriptorForCat();
  /*package*/ final ConceptDescriptor myConceptDog = createDescriptorForDog();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAnimals, myConceptCanvas, myConceptCat, myConceptDog);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Animals:
        return myConceptAnimals;
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Cat:
        return myConceptCat;
      case LanguageConceptSwitch.Dog:
        return myConceptDog;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAnimals() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Animals", "Animals", 0xee886be0abf5408eL, 0x8219419e0e49cb3cL, 0x4e93ae19daa212d0L);
    b.class_(false, true, false);
    b.origin("r:984c77fc-91fc-4536-816f-160192469f2f(Animals.structure)/5662060582600315600");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Animals", "Canvas", 0xee886be0abf5408eL, 0x8219419e0e49cb3cL, 0x4e93ae19daa212ddL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:984c77fc-91fc-4536-816f-160192469f2f(Animals.structure)/5662060582600315613");
    b.version(2);
    b.aggregate("animals", 0x4e93ae19daa212e0L).target(0xee886be0abf5408eL, 0x8219419e0e49cb3cL, 0x4e93ae19daa212d0L).optional(true).ordered(true).multiple(true).origin("5662060582600315616").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCat() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Animals", "Cat", 0xee886be0abf5408eL, 0x8219419e0e49cb3cL, 0x4e93ae19daa212d7L);
    b.class_(false, false, false);
    b.super_("Animals.structure.Animals", 0xee886be0abf5408eL, 0x8219419e0e49cb3cL, 0x4e93ae19daa212d0L);
    b.origin("r:984c77fc-91fc-4536-816f-160192469f2f(Animals.structure)/5662060582600315607");
    b.version(2);
    b.property("name", 0x4e93ae19daa212d8L).type(PrimitiveTypeId.STRING).origin("5662060582600315608").done();
    b.property("weight", 0x4e93ae19daa212daL).type(PrimitiveTypeId.INTEGER).origin("5662060582600315610").done();
    b.alias("cat");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDog() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Animals", "Dog", 0xee886be0abf5408eL, 0x8219419e0e49cb3cL, 0x4e93ae19daa212d1L);
    b.class_(false, false, false);
    b.super_("Animals.structure.Animals", 0xee886be0abf5408eL, 0x8219419e0e49cb3cL, 0x4e93ae19daa212d0L);
    b.origin("r:984c77fc-91fc-4536-816f-160192469f2f(Animals.structure)/5662060582600315601");
    b.version(2);
    b.property("name", 0x4e93ae19daa212d2L).type(PrimitiveTypeId.STRING).origin("5662060582600315602").done();
    b.property("weight", 0x4e93ae19daa212d4L).type(PrimitiveTypeId.INTEGER).origin("5662060582600315604").done();
    b.alias("dog");
    return b.create();
  }
}
